version: '3'

services:

  laravel:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    image: laravel-php
    container_name: laravel
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - net

  composer:
    restart: 'no'
    container_name: "composer"
    image: "composer"
    command: "install"
    volumes:
      - .:/app
    networks:
      - net

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    env_file: 
      - ./.env
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - net

  mysql:
    container_name: "mysql"
    restart: unless-stopped
    image: mysql:5.7
    env_file: 
      - ./docker/mysql.env
    volumes:
      - data:/var/lib/mysql
      - ./docker/mysql/mysql.sql:/docker-entrypoint-initdb.d/mysql.sql
    ports:
      - "3307:3306"
    networks:
      - net

  phpmyadmin:
    container_name: "phpmyadmin"
    restart: unless-stopped
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    ports:
      - "8081:80"
    networks:
      - net

  setup:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    image: laravel-php
    restart: 'no'
    container_name: setup
    command: "bash /wait-for-it.sh mysql:3306 -- sh -c 'sleep 40 && php artisan key:generate && php artisan migrate:refresh --seed && php artisan passport:install && php artisan storage:link && php artisan config:cache'"
    depends_on:
      - mysql
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/setup/wait-for-it.sh:/wait-for-it.sh
    networks:
      - net


volumes:
  data:
    driver: local
networks:
  net:
